# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintApp/ui/paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(750, 100, 81, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pencil = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Pencil.setObjectName("Pencil")
        self.verticalLayout.addWidget(self.Pencil)
        self.Eraser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Eraser.setObjectName("Eraser")
        self.verticalLayout.addWidget(self.Eraser)
        self.ColorSelector = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ColorSelector.setObjectName("ColorSelector")
        self.verticalLayout.addWidget(self.ColorSelector)
        self.ColorDisplayFrame = QtWidgets.QFrame(self.centralwidget)
        self.ColorDisplayFrame.setGeometry(QtCore.QRect(10, 370, 161, 171))
        self.ColorDisplayFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.ColorDisplayFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ColorDisplayFrame.setObjectName("ColorDisplayFrame")
        self.MainZone = QtWidgets.QFrame(self.centralwidget)
        self.MainZone.setGeometry(QtCore.QRect(180, 50, 561, 491))
        self.MainZone.setFrameShape(QtWidgets.QFrame.Box)
        self.MainZone.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MainZone.setLineWidth(2)
        self.MainZone.setObjectName("MainZone")
        self.DrawingFrame = QtWidgets.QFrame(self.MainZone)
        self.DrawingFrame.setGeometry(QtCore.QRect(19, 19, 521, 451))
        self.DrawingFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.DrawingFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrawingFrame.setLineWidth(2)
        self.DrawingFrame.setObjectName("DrawingFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Pencil.setText(_translate("MainWindow", "Pencil"))
        self.Eraser.setText(_translate("MainWindow", "eraser"))
        self.ColorSelector.setText(_translate("MainWindow", "Color Selector"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
