# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintApp/ui/paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qdrawer(object):
    def setupUi(self, Qdrawer):
        Qdrawer.setObjectName("Qdrawer")
        Qdrawer.resize(500, 500)
        Qdrawer.setMaximumSize(QtCore.QSize(500, 500))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Qdrawer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 164, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Pencil = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Pencil.setObjectName("Pencil")
        self.horizontalLayout.addWidget(self.Pencil)
        self.eraser = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.eraser.setObjectName("eraser")
        self.horizontalLayout.addWidget(self.eraser)

        self.retranslateUi(Qdrawer)
        QtCore.QMetaObject.connectSlotsByName(Qdrawer)

    def retranslateUi(self, Qdrawer):
        _translate = QtCore.QCoreApplication.translate
        Qdrawer.setWindowTitle(_translate("Qdrawer", "Form"))
        self.Pencil.setText(_translate("Qdrawer", "Pencil"))
        self.eraser.setText(_translate("Qdrawer", "eraser"))
