# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintApp/ui/paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qdrawer(object):
    def setupUi(self, Qdrawer):
        Qdrawer.setObjectName("Qdrawer")
        Qdrawer.resize(500, 500)
        Qdrawer.setMaximumSize(QtCore.QSize(500, 500))
        self.Pencil = QtWidgets.QPushButton(Qdrawer)
        self.Pencil.setGeometry(QtCore.QRect(450, 20, 41, 23))
        self.Pencil.setObjectName("Pencil")

        self.retranslateUi(Qdrawer)
        QtCore.QMetaObject.connectSlotsByName(Qdrawer)

    def retranslateUi(self, Qdrawer):
        _translate = QtCore.QCoreApplication.translate
        Qdrawer.setWindowTitle(_translate("Qdrawer", "Form"))
        self.Pencil.setText(_translate("Qdrawer", "Pencil"))
